#!/bin/bash


if [[ $(grep "^default-authentication-plugin=mysql_native_password" /etc/my.cnf | wc -l) == 0 ]]; then
temp_password=$(grep 'temporary password' /var/log/mysqld.log | awk 'NF>1{print $NF}')

#mysql -u root --connect-expired-password -p"${temp_password}" -N -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'RKTwC2gfWU2e58mrz8px*';"
mysql -u root -p'RKTwC2gfWU2e58mrz8px*' -N -e "UNINSTALL COMPONENT 'file://component_validate_password';"
mysql -u root -p'RKTwC2gfWU2e58mrz8px*' -N -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';"

fi
