#!/bin/bash


if [[ $(grep "default-authentication-plugin=mysql_native_password" /etc/my.cnf | wc -l) == 0 ]]; then

temp_password=$(grep 'temporary password' /var/log/mysqld.log | awk 'NF>1{print $NF}')
mysql -u root -p"${temp_password}" -N -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '';"
mysql -u root -N -e "UNINSTALL COMPONENT 'file://component_validate_password';"
mysql -u root -N -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';"

fi
